### ISSUE TITLE
Check integration of CN market

### ISSUE THREAD

**Issue by ReneNulschDE** [ReneNulschDE/mbapi2020#108]
Check if https://github.com/gnep88/mbapi2020 can be integrated 
@gnep88: Are your changes work for china?

**Comment by gnep88** [comment]
Hi @ReneNulschDE,
I am actually about to write the same thing to you - glad that you did it first ;)

Yes I can confirm it worked well for me and I have not observed any issues till now.

For the CN market integration, I changed directly in the ECE configs (as you can see in the diff). Would appreciate if you can find a place to integrate those changes since I think it needs some changes in the code as CN is quite different comparing to other markets. Thanks!

**Comment by ReneNulschDE** [comment]
Let me try to integrate your changes in an extra branch and I'll let you know any questions and when its ready to test. OK? THANKS

**Comment by gnep88** [comment]
Sure just one additional comment:
the Locale and Accept-language in the request header might not need to be changed, as they should be my device specific which I set in the iOS country and language settings. I do not think the server validates these two parts…

Anyway just give me a hint when it’s ready and I can change my HACS config for some tests… Thanks!

**Comment by gnep88** [comment]
One more thing @ReneNulschDE ,
it is possible to use both email address and/or mobile phone numbers (with country code prefix) as username - meanwhile it’s quite popular for CN market to use mobile phone numbers… I had tried both and it worked well, if a mobile phone number is provided you will receive an SMS (instead of an email) with verification code/pin to be input into the configuration flow.

you might want to add this hint/text in the HA configuration flow…

**Comment by ReneNulschDE** [comment]
Hi @gnep88 ,

i can't create an mbme account in china without an Chinese mobile phone. Could you create an account with the email address mb.dev.cn@nulsch.de and send me the password to this mail address?

**Comment by ReneNulschDE** [comment]
Hi @gnep88,

the master branch contains an early version for the Chinese market integration. Was not able to test it (no account), may I ask you to take a look.

**Comment by gnep88** [comment]
@ReneNulschDE sure I am glad to contribute. I tested and the login was successful but sensors are not generated. 

See Logs below seems that the country setting in the login window is not reflected in the URL endpoints used. Would you please take a look? Thanks 

 
Logger: custom_components.mbapi2020.websocket
Source: custom_components/mbapi2020/websocket.py:132 
Integration: MercedesME 2020 ([documentation](https://github.com/ReneNulschDE/mbapi2020), [issues](https://github.com/ReneNulschDE/mbapi2020/issues)) 
First occurred: 09:56:59 (5 occurrences) 
Last logged: 09:57:40

Could not connect to wss://websocket.amap-prod.mobilesdk.mercedes-benz.com/ws, retry in 10 seconds...

**Comment by ReneNulschDE** [comment]
@gnep88 - thx for testing. I have fixed this in the beta release v0.9.0b2 - may I ask you to recheck again?

**Comment by gnep88** [comment]
@ReneNulschDE I can confirm it works now with v0.9.0b2. Thanks a lot!
