### ISSUE TITLE
Some range_electric attributes have disappeared in release 0.9.5

### ISSUE THREAD

**Issue by DragonNZ** [ReneNulschDE/mbapi2020#144]
Hi,

I don't appear to have the attributes chargingPower and endOfChargeTime in range_electric any more.
You were adding the day of week in the latest release.
Have these attributes moved to another entity?

Thanks
   John

**Comment by DragonNZ** [comment]
Hi Rene,

My sincere apologies, I didn't realise that the attributes could appear and disappear dependent on state.
So yes, plugged in and charging the attributes are there.

Where do I find the day of week attribute that you added?

This is what I see under range_electric (cut off VIN)

![range_electric](https://github.com/ReneNulschDE/mbapi2020/assets/4507081/21d3f0e4-8e53-4b94-875f-347f7b1fe152)

Thanks
   John

**Comment by ReneNulschDE** [comment]
Hi John, 

no problem at all and no reason to apologize. 

The other attribute will only appear when the charging will not be finished on the current day. (Assumption based on my tests)

**Comment by DragonNZ** [comment]
HI Rene,

In the screenshot you will see that the end charge time is 6:00am, which is on the 12th Oct and the timestamp shows today 11th Oct.
So definitely not finishing on the current day but still not showing, so I wonder if it applicable only when the charging time is longer than 24 hours. Maybe it will appear then,

I will check again next time the car is lower on charge and will exceed 24 hours charging time.

I also think that the car will support it as on the MB Android app, it shows the end charge date and time.

Thanks,
  John

**Comment by ReneNulschDE** [comment]
mmmhhh, could you share some more details? Lets take a view on the messages between your HA and the MB Servers.

- Plug in the charging cable and start charging
- Go to the configuration (“Configure”) dialog of the integration and enable the “Debug only: Enable save…” option and click submit
- Restart HA
- Wait 2min
- Go to the configuration (“Configure”) dialog of the integration and disable the “Debug only: Enable save…” option and click submit
- Zip all files that you find in the folder “%HA-Config-Folder%/custom_components/mbapi2020/messages”
- send this zip-file to [mb.dev.github.144@nulsch.de](mailto:mb.dev.github.144@nulsch.de) 

Then I can check if the "endOfChargeTimeWeekday" is present and filled.

Otherwise, we can calculate the correct value with a template sensor. (Pseudocode: IF endofchargetime < currentime THEN Today+1+endofchargetime ELSE Today+endofchargetime)
