### ISSUE TITLE
Charging Power missing

### ISSUE THREAD

**Issue by markus76** [ReneNulschDE/mbapi2020#165]
Hi,
Why is charging power not supported anymore?
Thanks for your work 
regards 
markus [
![IMG_5078](https://github.com/ReneNulschDE/mbapi2020/assets/15011452/fd58a5b3-9e1b-400d-8dc9-96050a6b88f0)
](url)

**Comment by ReneNulschDE** [comment]
Hi,

This happens when the MBApi does not deliver the chargingpower information at HA Startup.

You can first test two things. Next time when your car is loading check if the attribute chargingpower becomes visible in your rangeelectric sensor. If this happens try to restart ha when the car is loading. Please report back if this works.

There are multiple reports of this problem and unfortunately it is not happening with my car. Therefore it's hard to solve. I'm working on a idea that a different user shared.

**Comment by ReneNulschDE** [comment]
@markus76 : Do you have a home assistant community account? If yes, could you share the user name in case you want to test something out and let me know your home country.

**Comment by markus76** [comment]
Hi,
my account name is also „markus76“ at home assistant community 
My home country ist Germany 
Yes of course iam interested in testing

**Comment by ReneNulschDE** [comment]
Fixed with release [v0.9.9](https://github.com/ReneNulschDE/mbapi2020/releases/tag/v0.9.9)

Thanks for your testing!
